# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d89b78b55c70ed7443aa0306c751e0e2b0c9d3f21db3d865d0317a0c8c2b4dd277c8276c74bf49fa970991dd4d33050704cf2042228c471bca2c547e8ba9b0c6

test:
  secret_key_base: 437d12cbc91eafd683164cbe430c412dbc4ed1d674bb4d11ddc611c1a3f37ef7a39ff19aa21670d84c85d9e8830835e67296bfa44822bc2a29f2a66244507d87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
